# Generated by Django 2.0.3 on 2018-07-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
