# Generated by Django 2.0.2 on 2018-03-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='dex_num',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
