# Generated by Django 2.0.2 on 2018-03-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20180318_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='dex_num',
            new_name='dex',
        ),
    ]
