# Generated by Django 2.0.3 on 2018-03-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20180318_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('eff', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=200)),
                ('cat', models.CharField(max_length=200)),
                ('pow', models.CharField(max_length=50)),
                ('acc', models.CharField(max_length=50)),
                ('pp', models.CharField(max_length=50)),
                ('tm', models.BooleanField(default=False)),
            ],
        ),
    ]
