# Generated by Django 2.0.3 on 2018-04-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_auto_20180331_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
    ]
